DEBUG: ''
logging:
    level:
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: ''
server:
    port: 8080

spring:
    jpa:
        open-in-view: 'true'
        database-platform: org.hibernate.dialect.H2Dialect
#        defer-datasource-initialization: 'true'
        hibernate:
            ddl-auto: none
    datasource:
        username: sa
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        password: ''
    sql:
        init:
            mode: always
    h2:
        console:
            enabled: 'true'
            path: /h2-console